@startuml

abstract class WebServiceClient {
+Register()
+Update(data, sender)
+Fail(messages, sender)
+Create(element, sender)
+Save(element, sender)
+Load(element, sender)
+LoadAll(sender)
+Delete(element, sender)
+{abstract}init()
}
class WebServiceClientAblageType {
+init()
}

abstract class ViewModelForm {
+ViewModelForm(webServiceClient)
+Register()
+Update(data, sender)
+Fail(messages, sender)
+create(element, sender)
+save(element, sender)
+load(element, sender)
+delete(element, sender)
+undoAllChanges()
+updateAllListeners()
+{abstract}init()
#{abstract}_createModel()
#{abstract}_createPropertyListeners()
#{abstract}_updateAllPropertyListeners()
#_registerToWebServiceClient()
-_initModel()
-_initPropertyListeners()
}
class ViewModelFormAblageType {
+ViewModelFormAblageType(webServiceClient)
+getBezeichnung()
+setBezeichnung(bezeichnung)
+init()
#_createModel()
#_createPropertyListeners()
#_updateAllPropertyListeners()
}

WebServiceClient <|-- WebServiceClientAblageType
ViewModelForm <|-- ViewModelFormAblageType

WebServiceClient <. ViewModelForm
WebServiceClientAblageType <- ViewModelFormAblageType

@enduml
