@startuml
rectangle **Material** {
    rectangle Metall
    rectangle Legierung
    rectangle Bronze
    rectangle Kupfer
    rectangle Eisen
    rectangle Ton
    rectangle Graphitton
    Metall --> Legierung
    Metall --> Kupfer
    Metall --> Eisen
    Legierung --> Bronze
    Ton --> Graphitton
}
@enduml
